FASTTEXT_EMBEDDIG_PATH = "embedding/wiki.en.bin"
#Dimension of the word embeddings.
EMB_DIMENSION_SIZE = 300
#Embedding size of AutoEncoder embedding
AE_EMB_DIMENSION_SIZE = 150
NUM_EPOCHS = 50 
BATCH_SIZE = 256
RANDOM_SEED = 1234
LEARNING_RATE = 1e-3
TUPLE_SAMPLE_SIZE = 20
AUTOENCODER_THRESHOLD = 0.95
IGNORE_NUMERIC_COLS = True